# Generated by Django 4.0 on 2021-12-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Delivery Received'), ('TRANSPORTING', 'Transporting'), ('DELIVERED', 'Delivered')], default=('PENDING', 'Pending'), max_length=20)),
                ('condition', models.CharField(choices=[('HEAT INTOLERANT', 'Heat intolerant'), ('WATER/MOIST INTOLERANT', 'Water/Moist intolerant'), ('PERISHABLE', 'Perishable'), ('FRAGILE', 'Fragile')], max_length=30, null=True)),
                ('address', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('receiver', models.CharField(max_length=50, verbose_name="receiver's name")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'verbose_name': 'Orders Made',
                'verbose_name_plural': 'Orders Made',
            },
        ),
    ]
