# Generated by Django 3.2.9 on 2021-11-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Delivery Received'), ('TRANSPORTING', 'Transporting'), ('DELIVERED', 'Delivered')], max_length=20, null=True),
        ),
    ]
