# Generated by Django 3.2.9 on 2021-11-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('HEAT INTOLERANT', 'Heat intolerant'), ('WATER/MOIST INTOLERANT', 'Water/Moist intolerant'), ('PERISHABLE', 'Perishable'), ('FRAGILE', 'Fragile')], max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='condition',
            field=models.ManyToManyField(to='order.STATE'),
        ),
    ]
