# Generated by Django 3.2.9 on 2021-12-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('order', '0003_auto_20211129_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='condition',
            field=models.ManyToManyField(to='order.State'),
        ),
    ]
