# Generated by Django 3.2.9 on 2021-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211203_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='condition',
            field=models.ManyToManyField(to='order.State'),
        ),
    ]
