# Generated by Django 3.2.9 on 2021-12-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_delivery_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='condition',
        ),
        migrations.AddField(
            model_name='delivery',
            name='condition',
            field=models.CharField(choices=[('HEAT INTOLERANT', 'Heat intolerant'), ('WATER/MOIST INTOLERANT', 'Water/Moist intolerant'), ('PERISHABLE', 'Perishable'), ('FRAGILE', 'Fragile')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='STATE',
        ),
    ]
