# Generated by Django 3.2.9 on 2021-12-03 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_auto_20211203_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
