# Generated by Django 3.2.9 on 2021-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
